include: package:effective_dart/analysis_options.1.2.2.yaml

linter:   
  rules:
    public_member_api_docs: false         
    type_annotate_public_apis: false     
    lines_longer_than_80_chars: false     
    use_setters_to_change_properties: false
    avoid_classes_with_only_static_members: false
