name: modular
repository: https://github.com/Flutterando/modular

ignore:
  - deprecated/**

packages:
  - modular_core
  - flutter_modular
  - shelf_modular
  - plugins/*
  # examples
  - flutter_modular/example
  - shelf_modular/example
  - plugins/modular_triple_bind/example
  - plugins/modular_bloc_bind/example


scripts:
  test:
    exec: flutter test --coverage