name: modular_core
description: Smart project structure with dependency injection and route management
version: 2.0.3+1
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ">=1.1.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  modular_interfaces: ">=2.0.2 <3.0.0"


dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
