name: shelf_modular
description: Smart project structure with dependency injection and route management
version: 2.1.0
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  shelf: ">=1.3.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  modular_core: ">=3.0.0-alpha.0 <4.0.0"
  mime: ">=1.0.2 <2.0.0"
  http_parser: ">=4.0.1 <5.0.0"
  web_socket_channel: ">=2.2.0 <3.0.0"
  shelf_web_socket: ">=1.0.1 <2.0.0"
  result_dart: ">=1.0.5 <2.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  lints: ^1.0.1
  test: ">=1.16.0 <2.0.0"
