name: shelf_modular
description: Smart project structure with dependency injection and route management
version: 3.0.1
homepage: https://github.com/Flutterando/modular

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  shelf: ">=1.3.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  modular_core: ^3.4.0
  mime: ^2.0.0
  http_parser: ">=4.0.1 <5.0.0"
  web_socket_channel: ^2.4.0
  shelf_web_socket: ">=1.0.1 <2.0.0"
  result_dart: ">=2.1.0 <3.0.0"

dev_dependencies:
  mocktail: ^1.0.4
  flutterando_analysis: ^0.0.2
  test: ">=1.16.0 <2.0.0"
