name: shelf_modular
description: Smart project structure with dependency injection and route management
version: 2.0.1
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  shelf: ">=1.3.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  modular_core: ">=2.0.1 <3.0.0"
  mime: ">=1.0.2 <2.0.0"
  http_parser: ">=4.0.1 <5.0.0"
  web_socket_channel: ">=2.2.0 <3.0.0"
  shelf_web_socket: ">=1.0.1 <2.0.0"

dev_dependencies:
  mocktail: ^0.1.4
  lints: ^1.0.1
  test: ^1.17.12
