name: shelf_modular
description: Smart project structure with dependency injection and route management
version: 3.0.0-beta.1
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ">=1.3.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  modular_core: ^3.3.3
  mime: ">=1.0.2 <2.0.0"
  http_parser: ">=4.0.1 <5.0.0"
  web_socket_channel: ">=2.2.0 <3.0.0"
  shelf_web_socket: ">=1.0.1 <2.0.0"
  result_dart: ">=1.0.5 <2.0.0"

dependency_overrides:
  modular_core:
    git:
      url: https://github.com/necodeIT/modular.git
      path: modular_core

dev_dependencies:
  mocktail: ^0.3.0
  flutterando_analysis: ^0.0.2
  test: ">=1.16.0 <2.0.0"
