library flutter_modular;

export 'src/exceptions/modular_error.dart';
export 'src/inject/bind.dart';
export 'src/inject/inject.dart';
export 'src/interfaces/child_module.dart';
export 'src/interfaces/disposable.dart';
export 'src/interfaces/main_module.dart';
export 'src/interfaces/route_guard.dart';
export 'src/modular_base.dart';
export 'src/navigator/modular_navigator_interface.dart';
export 'src/routers/route_link.dart';
export 'src/routers/router.dart';
export 'src/widgets/consumer_widget.dart';
export 'src/widgets/modular_app.dart';
export 'src/widgets/modular_stateful_widget_state.dart';
export 'src/widgets/modular_stateless_widget.dart';
export 'src/widgets/module_widget.dart';
export 'src/widgets/router_outlet.dart';
