///Implements [Exception], creating an error class for
///Modular, overrides [toString] to return the desired
///[stackTrace]
abstract class ModularError implements Exception {
  /// Message received by the error
  final String message;

  /// Stack Trace generated by the error

  final StackTrace? stackTrace;

  /// [ModularError] constructor, receives [message] and [stackTrace]
  const ModularError(this.message, [this.stackTrace]);

  String _returnStackTrace() =>
      stackTrace != null ? '\n${stackTrace.toString()}' : '';

  @override
  String toString() => '$runtimeType: $message${_returnStackTrace()}';
}
