name: modular_codegen
description: Code Generate for flutter_modular. Inject Automation. Annotation @Inject, @Param and @Data. 
version: 3.0.4
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_modular_annotations: ^0.0.2
  analyzer: ">=2.0.0 <3.2.0"
  glob: ^2.0.0
  build: '>=2.1.0 <3.0.0'
  build_resolvers: '>=2.0.0 <2.1.0'
  source_gen: ^1.0.0
  meta: ">=1.3.0 <2.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  build_config: ">=1.0.0 <1.1.0"
  build_runner: ">=2.1.0 <3.0.0"
  build_test: ^2.0.0
  test: ^1.16.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
