name: modular_test
description: Smart project structure with dependency injection and route management
version: 2.0.1
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  modular_core: ">=2.0.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10