name: modular_triple_bind
description: Smart project structure with dependency injection and route management
version: 1.0.0
homepage: https://github.com/Flutterando/modular

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  triple: '>=1.5.0 <2.0.0'
  flutter_modular: ">=5.0.0 <6.0.0"
  modular_interfaces: ">=2.0.0 <3.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.0
  
flutter: 
