name: modular_interfaces
description: Smart project structure with dependency injection and route management
version: 2.0.2
homepage: https://github.com/Flutterando/modular
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
