name: CI

on: 
  pull_request:
    branches: 
      - master
jobs:
  flutter_modular:
    name: flutter modular
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.41.7'
    
    - name: get packages
      run: flutter pub get
      working-directory: flutter_modular
    
    - name: Flutter Test
      run: flutter test --coverage --coverage-path ../coverage/lcov.info
      working-directory: flutter_modular
      
    - name: Codecov GitHub Action
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  modular_core:
    name: modular core
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.41.7'
    
    - name: get packages
      run: flutter pub get
      working-directory: modular_core
    
    - name: Flutter Test
      run: flutter test --coverage --coverage-path ../coverage/lcov.info
      working-directory: modular_core
      
    - name: Codecov GitHub Action
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
  shelf_modular:
    name: shelf modular
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.41.7'
    
    - name: get packages
      run: flutter pub get
      working-directory: shelf_modular
    
    - name: Flutter Test
      run: flutter test --coverage --coverage-path ../coverage/lcov.info
      working-directory: shelf_modular
      
    - name: Codecov GitHub Action
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

